#Git commands:

print("\n", "-"*58, "\n")
print(" Hello\n this is the usefull commands for Git:\n")
print(" 1-  git init      : Initialized empty Git repository.")
print(" 2-  git add -A    : Add all file to stage.")
print(" 3-  git commit    : Commit files that are on stage.")
print(" 4-  git status    : Status of git repo.")
print(" 5-  git log       : Log of git repo.")
print(" 6-  git diff      : Difference between old and new files.")
print(" 7-  git reset     : Reset changes.")
print(" 8-  git branch    : Working with branches.")
print(" 9-  git checkout  : Changing work branch.")
print(" 10- git merge     : Merging branches with master branch.")
print(" 11- git rm files  : Removing files.")
print(" 12- git branch -d : Deleting branch.")
print(" 13- git clone add : Cloning repo from address.")
print(" 14- git pull addr : Pulling repo from address.")
print(" 15- git push addr : Pushing repo to addreaa.")
print(" 16- git show id   : Show the log if id place.")
print(" 17- git tag -a v2 : Taging the version of repo.")
print("\n", "by AH_VAHED :) : https://github.com/AmirHosein-Vahed", "\n", "-"*58, "\n")
